name: LiveOCR Reader fix

on:
  push:
    tags: ["v*"]
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        shell: pwsh
        run: npm ci

      # Build OCR runtime (so we never miss the EXE)
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"   # LiveRouteOCR targets net6.0

      - name: Publish LiveRouteOCR
        shell: pwsh
        run: dotnet publish .\LiveRouteOCR\LiveRouteOCR.csproj -c Release -r win-x64 -p:PublishSingleFile=false -p:SelfContained=true -o LiveRouteOCR/publish

      - name: Ensure OCR publish output exists
        shell: pwsh
        run: |
          if (-not (Test-Path "LiveRouteOCR/publish/LiveRouteOCR.exe")) {
            Write-Error "Missing LiveRouteOCR/publish/LiveRouteOCR.exe"; exit 1
          }

      - name: Build app (renderer + package)
        shell: pwsh
        run: npm run dist   # builds Vite + packs to release/

      - name: List release contents
        shell: pwsh
        run: |
          Write-Host "---- RELEASE TREE ----"
          Get-ChildItem -Path "release" -Recurse | Select-Object FullName,Length,LastWriteTime

      - name: Verify OCR binary packaged
        shell: pwsh
        run: |
          $p = Get-ChildItem -Path "release\win-unpacked\resources\LiveRouteOCR\LiveRouteOCR.exe" -ErrorAction SilentlyContinue
          if (-not $p) {
            Get-ChildItem -Path "release\win-unpacked\resources" -Recurse | Select FullName,Length | Out-String | Write-Host
            Write-Error "Packaged app is missing LiveRouteOCR.exe"; exit 1
          } else {
            Write-Host "Found packaged: $($p.FullName)"
          }

      - name: Create/Update GitHub Release and upload
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/**/*.exe
            release/**/*.msi
            release/**/*.zip
            release/**/*.yml
            release/**/*.blockmap
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
